### PR TITLE
Darken the input field to make unsent text readable

### PR DESCRIPTION
**Pull request by ithinuel**

### CODE REVIEW

**Comment by SpartanJ** [comment]
Hi @ithinuel !
I'm a little big confused over this patch, currently we have this:
```css
html[dir] ._3uMse {
    margin: 5px 10px;
    padding: 9px 12px 11px;
    background-color: var(--compose-input-background);
    border: 1px solid var(--compose-input-border);
    border-radius: 21px;
}
```
In which case we would need this change?
Can you show me a couple of screenshots with the visual difference applying the patch? That might help.

Thanks!!

**Comment by SpartanJ** [comment]
I'm thinking, maybe you have dark mode enabled in the WhatsApp settings? Because this style is designed to work with the default light theme.

**Comment by ithinuel** [comment]
Hi @SpartanJ  thanks for your SUPER quick review !

I was not aware of theme setting in the webapp.
It was actually set to system's theme (I don't know how it's called en in English version). I confirm it works fine if I select either dark or light.

Thanks you for the hint ;) !

**Comment by SpartanJ** [comment]
No problem! Regards!

**Pull request closed without merging**
